# Generated by Django 4.1.1 on 2022-10-07 23:34

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.TextField(default=userProfile.models.uuid_generator, primary_key=True, serialize=False)),
                ('bio', models.TextField(max_length=255, null=True)),
                ('skills', models.CharField(max_length=128)),
                ('pfp', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
