# Generated by Django 4.1.1 on 2022-10-09 18:30

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_alter_profile_bio_alter_profile_pfp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.TextField(default=userProfile.models.uuid_generator, editable=False, primary_key=True, serialize=False),
        ),
    ]
