# Generated by Django 4.1.1 on 2022-10-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile_email_profile_username_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default=models.CharField(blank=True, max_length=54, null=True), max_length=54, null=True),
        ),
    ]
