# Generated by Django 4.1.1 on 2022-10-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default=models.CharField(blank=True, max_length=60, null=True), max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
