# Generated by Django 4.1.1 on 2022-10-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_alter_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayName',
            field=models.CharField(blank=True, default=None, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=54, null=True),
        ),
    ]
