# Generated by Django 4.1.1 on 2022-11-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_alter_profile_displayname_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinned',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotlightProj',
            field=models.JSONField(default=None),
        ),
    ]
