# Generated by Django 4.1.1 on 2022-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_profile_pinned_profile_spotlightproj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pinned',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotlightProj',
            field=models.JSONField(default=None, null=True),
        ),
    ]
