# Generated by Django 4.1.2 on 2022-10-28 16:25

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('pid', models.TextField(default=projects.models.uuid_generator, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('users', models.JSONField()),
                ('languages', models.JSONField()),
                ('user_friendly', models.BooleanField(default=False)),
            ],
        ),
    ]
