# Generated by Django 4.1.2 on 2022-10-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_friendly',
            new_name='beg_friendly',
        ),
    ]
