# Generated by Django 4.1.1 on 2022-11-28 01:15

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.TextField(default=project.models.uuid_generator, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('users', models.JSONField()),
                ('languages', models.JSONField()),
                ('beg_friendly', models.BooleanField(default=False)),
            ],
        ),
    ]
